### ISSUE TITLE
Privacy and Security Concerns

### ISSUE THREAD

**Issue by kratz00** [asdil12/ff-map#2]
ff-map uses external java-script (jquery and bootstrap) which are not hosted on the same server, instead they are served by content delivery networks (CDNs) , namely Google and MaxCDN.
I know about the pros of doing it like it is done here but for me the cons are more concerning:

* privacy issues by logging of all our users ip addresses
* tracking of all our users by cookies etc.
* trust, who guarantees that the java-script file was not tempered with (this could be solved with [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity))

What do you think about hosting the two java-script files ourselves? I would create a pull request if you agree.
Or do you have a better idea?

**Comment by asdil12** [comment]
Sure - I was just too lazy to doo that when I created the webui.
