### ISSUE TITLE
Default tile servers are slow sometimes and only support legacy IP

### ISSUE THREAD

**Issue by fblaese** [asdil12/ff-map#205]
The servers from RRZE used for the openstreetmap.de alternative tiles are way faster and also support IPv6.

We probably should use these servers for the default map style as well.

I find the Wikimedia Map style quite nice as well. It might be a good idea to replace the commercial Thunderforest maps with these. They have less contrast than the default map style, which makes nodes and meshes stand out more.

I've set up a demo for all these map styles here: https://aquarius.sgstbr.de/mapdemo/
The usage policy for RRZE tile servers are here: https://osm.rrze.fau.de/
For Wikimedia tiles it can be found here: https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use

**Comment by fblaese** [comment]
Pull Requests here: #208 and #207

**Comment by adschm** [comment]
Further discussion in PRs.
