### ISSUE TITLE
babel Version

### ISSUE THREAD

**Issue by fblaese** [asdil12/ff-map#210]
Ein zusätzliches Feld für die Version des Babel Daemons analog zur BATMAN Version wäre gut.

**Comment by adschm** [comment]
"babeld_version" in system_data?

Bau das mal auf zwei oder drei Routern in den nodewatcher ein (einfach ins Script packen), ich bau dann in ein paar Tagen den Code dazu.

Was machen wir bei den Knoten? Einfach weglassen?

**Comment by fblaese** [comment]
"babel_version". Man muss ja nicht zwingend babeld einsetzen.

Eigentlich ist das ganze in system_data wegen Modularisierung schlecht aufgehoben.
Besser wäre wohl ein eigener babel-Block, in dem dann auch die Nachbarn leben könnten.
Aber da das sowieso schon kaputt ist.. Mir eigentlich egal.

Und dann sollte der gesamte Versionsstring z.B. "babeld-1.9.1" lauten.


> Was machen wir bei den Knoten? Einfach weglassen?

Joa, da gibts das dann halt nicht.

Optimal wäre da dann noch, dass das Monitoring nur Felder anzeigt, die tatsächlich auch befüllt sind, aber das ist dann nur eine optische Aufhübschung.

**Comment by adschm** [comment]
> Aber da das sowieso schon kaputt ist.. Mir eigentlich egal.

Das war genau mein Argument.
Wenn man das modularisieren will, dann sollte man gleich die neue json Syntax bauen und einführen (ich habe mir Tims Firmware-Patch noch nicht genauer angesehen, das basiert ja glaube ich auf dem XML). Bei dem alten Zeug würde ich jetzt die Felder nicht plötzlich auf ein anderes Konzept umbauen, das dann nicht konsequent umgesetzt wird.

>  Und dann sollte der gesamte Versionsstring z.B. "babeld-1.9.1" lauten.

Das ist ja das, was babeld -V eh rauswirft? Bei Batman macht der master und openwrt-19.07 ja inzwischen auch Versionen wie "openwrt-2019.1-2".

> Optimal wäre da dann noch, dass das Monitoring nur Felder anzeigt, die tatsächlich auch befüllt sind, aber das ist dann nur eine optische Aufhübschung.

Ja, das sollte man mal ändern. Da geht dann aber glaube ich das Zwei-Spalten-Design kaputt, weil der Block auf der anderen Seite eine feste Höhe annimmt. Sollte man aber vll. mal ordentlich lösen. Die Event-Liste geht ja da teilweise auch kaputt.

**Comment by adschm** [comment]
Habs jetzt mal eingebaut und mit meinem GW getestet.
Bei wenigen Nachbarn sind ggf. die Blöcke links und rechts nicht gleich hoch.

Blöderweise schreibt babeld -V in stderr, daher ist das etwas umständlich:
[ -s /etc/config/babeld ] && SYSTEM_DATA=$SYSTEM_DATA"<babel_version>$(babeld -V 2>&1)</babel_version>"

Man kann jetzt auch die Routerliste nach der Version filtern:
z.B. babel:1\.9\.1
Regex aktiv!
