### ISSUE TITLE
Accommodate renamed interface br-client for WebUI link and highlighting

### ISSUE THREAD

**Issue by fblaese** [asdil12/ff-map#218]
With our latest firmware the client interface has been renamed from br-mesh to br-client.
Therefore, various things which rely on this interface (WebUI link generation, hightlighting of this interface, ..?) do not work anymore.

**Comment by adschm** [comment]
Ist mir heute früh auch eingefallen. Muss ich mir dringend ansehen.

**Comment by adschm** [comment]
Sollte hier behoben sein. Bitte aufmerksam beobachtet und ggf. Fehler melden:

https://github.com/FreifunkFranken/fff-monitoring/commit/bd8d0280f6609340312447e48a434aaf4e10c465
